### PR TITLE
dont want for loop, save cpu & mem

### PR DESCRIPTION
**Pull request by willywotz**

### CODE REVIEW

**Comment by tawan475** [comment]
This little program work by simulating a Chromium instance to bypass Cloudflare
And it only loop (clicking) once every 30 seconds

Which is not that CPU intensive but there is no other choice with ram other than bite the bullet

**Review by tawan475 — COMMENTED** [review]
Consider adding `document.getElementById('app').__vue__.accumulator = 800;`
in line number 26 for the first request to be 800 pops and not one

**Comment by willywotz** [comment]
จริงๆแล้ว click แรกมันชอบติด 503 ก็เลยไม่ได้สนใจ

**Comment by tawan475** [comment]
รู้สึกว่าเซืฟเค้าจะเน่านะครับ
`https://stats.popcat.click/pop?pop_count=800&captcha_token=XXX`
image

**Pull request merged**
